---

# Custom Authselect Profile
rhel8cis_authselect_custom_profile_name: aeron-profile

# Retain the Graphical User Interface (Server with GUI)
rhel8cis_desktop_required: true

# PAM Faillock Configurations
rhel8cis_rule_5_3_3_1_1: true
rhel8cis_rule_5_3_3_1_2: true
rhel8cis_rule_5_3_3_1_3: true

# Bypass GPG Key False Alarm (Specific to this VM's repo setup)
rhel8cis_rule_1_2_1_1: false

# Bypass Crypto-Policy/SELinux logical overrides (Already enforced locally)
rhel8cis_rule_1_6_1: false
rhel8cis_rule_1_6_2: false
rhel8cis_rule_1_6_3: false
rhel8cis_rule_1_6_4: false

# Bypass GDM Banner (Upstream RHEL8-CIS role is missing the templates for this)
rhel8cis_rule_1_8_1: false
rhel8cis_rule_1_8_2: false
rhel8cis_rule_1_8_3: false
rhel8cis_rule_1_8_4: false
rhel8cis_rule_1_8_5: false
