---
- name: Applying RHEL8 CIS Hardening - aeron
  hosts: all
  become: true

  vars:
    # Just a banner assigned to me
    rhel8cis_warning_banner: "AIRNAV EXAM NODE - RON - AUTHORIZED USE ONLY"

    # Disable Level 2 to apply Level 1 on the hardening (Fact generation only)
    rhel8cis_level_2: false

    # Enabling the goss audit
    setup_audit: true
    run_audit: true

    rhel8cis_disruption_high: true

  pre_tasks:
    - name: Announce The run is started
      ansible.builtin.debug:
        msg: "The pre-task run is started"

    - name: Check if the VM is real using a almalinux 8
      ansible.builtin.assert:
        that:
          - ansible_distribution == "AlmaLinux"
          - ansible_distribution_major_version == "8"
        fail_msg: The system is not using almalinux 8
        success_msg: The system using almalinux 8 OS

    - name: To fully update the OS
      ansible.builtin.command: dnf update -y --disablerepo=epel
      changed_when: false

  post_tasks:
    - name: Announce The run is finished
      ansible.builtin.debug:
        msg: "The run for hardening using rhel8-cis is done."

  roles:
    - RHEL8-CIS
